### ISSUE TITLE
Are requests to fetch the order book cached?

### ISSUE THREAD

**Issue by ChristianCoenen** [gateio/rest-v4#4]
# Problem
Endpoint: ```GET /spot/order_book``` (v4)

I am currently building an internal order book as described [here](https://www.gate.io/docs/developers/apiv4/ws/en/#order-book-channel). After receiving the first update event from the WebSocket, I am fetching the order book through the REST API.

Doing so, I occasionally observe the following unexpected behaviour:
<details>
  <summary>Output</summary>
  
```
orderbook event: 1639987999796 (spot.order_book_update['t'])
fetch orderbook
orderbook event: 1639987999861
orderbook event: 1639988000093
orderbook event: 1639988000160
orderbook event: 1639988000278
orderbook event: 1639988000341
orderbook event: 1639988000589
orderbook event: 1639988000675
orderbook event: 1639988000780
orderbook event: 1639988000878
received an answer. timestamp: 1639987998897 (response['current'])
```
</details>

How can the REST call timestamp (```current```) be smaller than the timestamp when the request was sent out? Upon investigation and implementing a workaround for this problem (fetching again), I discovered the following:

<details>
  <summary>Output</summary>
  
```
orderbook event: 1639992489593
fetch orderbook
orderbook event: 1639992489844
orderbook event: 1639992489946
orderbook event: 1639992490041
orderbook event: 1639992490243
orderbook event: 1639992490347
orderbook event: 1639992490435
orderbook event: 1639992490545
orderbook event: 1639992490644
orderbook event: 1639992490733
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992490925
orderbook event: 1639992491037
orderbook event: 1639992491136
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992491235
orderbook event: 1639992491341
orderbook event: 1639992491434
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992491506
orderbook event: 1639992491638
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992491845
orderbook event: 1639992491940
orderbook event: 1639992492035
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992492092
orderbook event: 1639992492333
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992492448
orderbook event: 1639992492545
orderbook event: 1639992492645
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992492728
orderbook event: 1639992492840
orderbook event: 1639992492934
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992493038
orderbook event: 1639992493099
orderbook event: 1639992493242
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992493345
orderbook event: 1639992493437
orderbook event: 1639992493547
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992493635
orderbook event: 1639992493830
received an answer. timestamp: 1639992489005
fetch again
orderbook event: 1639992494041
orderbook event: 1639992494136
received an answer. timestamp: 1639992494303
```
</details>

This makes me wonder if there is some caching involved on your side? If so, it is not documented yet. If not, do you have any explanation for why this occurs? There is definitely no caching on my side.

Please let me know if you need additional information.

**Comment by revilwang** [comment]
1.HTTP order books are cached.
2. `current` means the time when the order book *response* is generated. The `t` field in WebSocket updates corresponds to the `update` field in HTTP response, which means the latest time the order book got updated.
3. The recommended way to maintain local order book is fetching HTTP result only when the WebSocket updates breaks your local order book. You can find an implementation example [here](https://github.com/gateio/gatews/tree/master/python/examples)

**Comment by ChristianCoenen** [comment]
Thanks for the information!
